version: '3.7'
x-build-image: &build-image
  build:
    context: .
    cache_from:
      - web-lambdas-terraform
      - quay.io/nyulibraries/web-lambdas-terraform
      - quay.io/nyulibraries/web-lambdas-terraform:${BRANCH_NO_SLASH}
      - quay.io/nyulibraries/web-lambdas-terraform:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
  environment:
    - BRANCH_NO_SLASH
    - CIRCLE_SHA1

services:
  web_lambdas_terraform_1:
    <<: *build-image
    image: web_lambdas_terraform
  web_lambdas_terraform_2:
    <<: *build-image
    image: "quay.io/nyulibraries/web-lambdas-terraform:latest"
    depends_on:
      - web_lambdas_terraform_1
  web_lambdas_terraform_3:
    <<: *build-image
    image: "quay.io/nyulibraries/web-lambdas-terraform:${BRANCH_NO_SLASH}"
    depends_on:
      - web_lambdas_terraform_2
    environment:
      - BRANCH_NO_SLASH
      - CIRCLE_SHA1
  web_lambdas_terraform_4:
    <<: *build-image
    image: "quay.io/nyulibraries/web-lambdas-terraform:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}"
    depends_on:
      - web_lambdas_terraform_3
    environment:
      - BRANCH_NO_SLASH
      - CIRCLE_SHA1