# Aliases
docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:19.03.13-dc-1.27.4-0
  working_directory: ~/app

auth_quay: &auth_quay
  run:
    name: Docker login
    command: docker login quay.io -u "$QUAY_USERNAME" --password "$QUAY_PASSWORD"

build_docker: &build_docker
  run:
    name: Build and tag Docker images
    command: docker-compose build

push_docker: &push_docker
  run:
    name: Push images to repository
    command: ~/scripts/push_quay.sh

version: 2.1
jobs:
  build-image:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - <<: *auth_quay
      - <<: *build_docker
      - <<: *push_docker

workflows:
  version: 2
  build:
    jobs:
      - build-image