# Aliases
docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:19.03.13-dc-1.27.4-0
      environment:
        - PROJECT_NAME=web-lambdas-terraform
  working_directory: ~/app

auth_quay: &auth_quay
  run:
    name: Docker login
    command: docker login quay.io -u "$QUAY_USERNAME" --password "$QUAY_PASSWORD"

build_docker: &build_docker
  run:
    name: Build and tag Docker images
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker-compose build

push_docker: &push_docker
  run:
    name: Push images to repository
    command: ./scripts/push_quay.sh

push_tagged_version: &push_tagged_version
  run:
    name: Push images to repository
    command: |
      docker-compose build web_lambdas_terraform_1
      docker tag web_lambdas_terraform quay.io/nyulibraries/${PROJECT_NAME}:${CIRCLE_TAG}
      docker push quay.io/nyulibraries/${PROJECT_NAME}:${CIRCLE_TAG}

version: 2.1
jobs:
  build-image:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - <<: *auth_quay
      - <<: *build_docker
      - <<: *push_docker

  tag-version:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - <<: *auth_quay
      - <<: *push_tagged_version

workflows:
  version: 2
  build:
    jobs:
      - build-image:
          filters:
            branches:
              only: /.*/
      - tag-version:
          filters:
            tags:
              only: /.*/